name: Publish to nuget
on:
  push:
    branches:
      - develop # Your default release branch
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Publish
      - name: Publish NuGet
        uses: rohith/publish-nuget@v1.2.0
        with:
           project_dir: Swashbuckle.AWSApiGateway.Annotations
        #   tag_format: v* # [*] gets replaced with version
           nuget_key: ${{secrets.NUGET_API_KEY}}
